{% set version = "0.4.0.dev20240919" %}

package:
  name: cargo-patch
  version: {{ version }}

source:
  url: https://github.com/itmettkeDE/cargo-patch/archive/f99685ff4f1783a41ab01e21885ad60013586614.zip
  sha256: 2c5ba7495dfbec29e94442b4f41fcd6798a20796d887e6231f323a0239423846
  patches:
    # FIXME: Remove once https://github.com/itmettkeDE/cargo-patch/pull/73 is merged
    - patches/0001-rust-edition-2024.patch

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
    - zlib  # [build_platform != target_platform and not (osx and arm64)]
  host:
    - openssl
    - zlib  # [not osx]

test:
  commands:
    # The command doesn't have a help command.
    - test -f $PREFIX/bin/cargo-patch

about:
  home: https://github.com/itmettkeDE/cargo-patch
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Cargo Subcommand which allows patching dependencies using patch files.
  dev_url: https://github.com/itmettkeDE/cargo-patch

extra:
  recipe-maintainers:
    - xhochy
