{% set version = "0.3.2" %}

package:
  name: cargo-patch
  version: {{ version }}

source:
  url: https://github.com/itmettkeDE/cargo-patch/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 41243074b5de18e8df15ee8d4ddd7bc5542b31c5cbbdd631c76aaf6a043169f8

build:
  number: 2
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('rust') }} 1.85
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - cargo-bundle-licenses
    - pkg-config
    - zlib  # [build_platform != target_platform and not (osx and arm64)]
  host:
    - openssl
    - zlib  # [not osx]

test:
  commands:
    # The command doesn't have a help command.
    - test -f $PREFIX/bin/cargo-patch

about:
  home: https://github.com/itmettkeDE/cargo-patch
  license: MIT
  license_family: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Cargo Subcommand which allows patching dependencies using patch files.
  dev_url: https://github.com/itmettkeDE/cargo-patch

extra:
  recipe-maintainers:
    - pavelzw
    - borchero
    - xhochy
