schema_version: 1

context:
  version: 0.4.0.dev20240919

package:
  name: cargo-patch
  version: ${{ version }}

source:
  url: https://github.com/itmettkeDE/cargo-patch/archive/f99685ff4f1783a41ab01e21885ad60013586614.zip
  sha256: 2c5ba7495dfbec29e94442b4f41fcd6798a20796d887e6231f323a0239423846
  patches:
    # FIXME: Remove once https://github.com/itmettkeDE/cargo-patch/pull/73 is merged
    - patches/0001-rust-edition-2024.patch

build:
  number: 3
  skip: win

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - cargo-bundle-licenses
    - cargo-auditable
    - pkg-config
    - if: build_platform != target_platform and not (osx and arm64)
      then: zlib
  host:
    - openssl
    - if: not osx
      then: zlib

tests:
  - script:
      - test -f $PREFIX/bin/cargo-patch

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: Cargo Subcommand which allows patching dependencies using patch files.
  homepage: https://github.com/itmettkeDE/cargo-patch
  repository: https://github.com/itmettkeDE/cargo-patch

extra:
  recipe-maintainers:
    - xhochy
